const addresses = [
    '4th Street',
    'Clark Street',
    'Fawn Lane',
    'Pheasant Run',
    'Queen Street',
    'Adams Street',
    'Rose Street',
    '3rd Avenue',
    'Church Street',
    'Magnolia Court',
    'Cobblestone Court',
    'Grove Avenue',
    'Franklin Avenue',
    'Briarwood Drive',
    'Sherman Street',
    '9th Street West',
    'Church Street South',
    'Summer Street',
    'Valley View Drive',
    'Holly Court',
    'Oak Avenue',
    'Walnut Avenue',
    'Mulberry Lane',
    'Main Street',
    'Prospect Avenue',
    'Wood Street',
    'Evergreen Drive',
    'Forest Drive',
    'Route 11',
    'Arch Street',
    'Clay Street',
    '1st Street',
    '8th Street West',
    'Durham Road',
    'Aspen Court',
    'Cottage Street',
    '12th Street East',
    'Redwood Drive',
    'West Street',
    'Olive Street',
    'Windsor Drive',
    '3rd Street West',
    'Edgewood Road',
    '13th Street',
    'Laurel Street',
    'Holly Drive',
    '5th Street West',
    'Delaware Avenue',
    'Brook Lane',
    'Cambridge Drive',
    'Bridge Street',
    'Oxford Court',
    'Grant Avenue',
    'Hamilton Street',
    'York Street',
    'Jones Street',
    'Fairway Drive',
    'Elm Avenue',
    'Schoolhouse Lane',
    'Cedar Court',
    'Sherwood Drive',
    'Market Street',
    'Route 70',
    '6th Street North',
    'Lafayette Street',
    'Ridge Avenue',
    'Sunset Drive',
    'Route 20',
    '5th Street',
    'Pine Street',
    'Front Street North',
    'Lafayette Avenue',
    'Creek Road',
    'Surrey Lane',
    'Windsor Court',
    'Chapel Street',
    'Maple Lane',
    'Manor Drive',
    'Tanglewood Drive',
    'Edgewood Drive',
    'Canterbury Road',
    'Church Road',
    'Pin Oak Drive',
    'Route 6',
    'Highland Drive',
    '5th Avenue',
    'Mechanic Street',
    '1st Avenue',
    'Henry Street',
    'Howard Street',
    'Route 100',
    'Linden Avenue',
    'Old York Road',
    'Lexington Court',
    'State Street',
    'Willow Drive',
    'Canal Street',
    'Country Club Road',
    'Jefferson Avenue',
    'Fairview Road',
];
export default addresses;
